Crud implementation
JasinskiyD/MyLinkedList pull request #7
Opened 2019-01-23 17:18 UTC by JasinskiyD

2019-01-23 18:24 UTC, sergey-chumachenko requested changes

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (element == null) {  // if element is invalid
please, move comment above code

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
>          return size == 0;
replace with following head == null

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (head == null) {  // if first element in list is null
replace with isEmpty()

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (indexInRange(index)) {
replace with negative operator

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (indexInRange(index)) {
see comment in row #53

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +                    currentValue = new Node(element);
currentValue. May be should be newNode?

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +            if (isEmpty()) {
seems this is useless

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (indexInRange(index)) {
revert condition

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +    private Node getLastNode() {
refactor this tone o Node getNode(int index);

2019-01-23 18:24 UTC, sergey-chumachenko commented on src/main/java/myLinkedList/MyLinkedList.java
> +        StringBuilder string = new StringBuilder();
please, replace this with StrBuilder form apache commons library

2019-01-23 21:45 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (element == null) {  // if element is invalid
done

2019-01-23 21:45 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
>          return size == 0;
done

2019-01-23 21:47 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (head == null) {  // if first element in list is null
done

2019-01-23 21:48 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (indexInRange(index)) {
done

2019-01-23 21:48 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +                    currentValue = new Node(element);
done

2019-01-23 21:48 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +            if (isEmpty()) {
done

2019-01-23 21:48 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (indexInRange(index)) {
done

2019-01-23 21:48 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +        if (indexInRange(index)) {
done

2019-01-30 19:20 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +        StringBuilder string = new StringBuilder();
StrBuilder is depracated
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/StrBuilder.html

2019-01-30 19:20 UTC, JasinskiyD commented on src/main/java/myLinkedList/MyLinkedList.java
> +    private Node getLastNode() {
done

2019-01-30 19:22 UTC, merged